@root = {{baseUrl}}/comments

@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzM2ZTIzYzljMWU5NjdmOWNlMGI5ODMiLCJlbWFpbCI6ImZhcmhhZEBnbWFpbC5jb20iLCJpYXQiOjE3MzE2NTAxMDksImV4cCI6MTczOTQyNjEwOX0.8krrYm5SnZJo7DzAtDgGI_Wp742OyeaTtBI00qFAhAk



### comment on a product

# @name comment
POST {{root}}
Content-Type: application/json
Authorization: {{authToken}}

{
    "comment": {
        "text": "Nice coffee!", 
        "photourls": [],
        "productId": "coffee_b2c4774c-41b1-4946-8937-61431af57594"
    }
}





### update a comment

# @name updateComment
PATCH {{root}}/6737b9e19bf99c750eab58c2
Content-Type: application/json
Authorization: {{authToken}}

{
    "text": "No i was"
}





### get my comments

# @name myComments

GET {{root}}
Content-Type: application/json
Authorization: {{authToken}}





### get my comments on a product

# @name myCommentsOnProduct
GET {{root}}/coffee_34713695-619c-4062-8db1-05c4f30a642d
Content-Type: application/json
Authorization: {{authToken}}

