@root = {{baseUrl}}/favorites
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzM2ZTIzYzljMWU5NjdmOWNlMGI5ODMiLCJlbWFpbCI6ImZhcmhhZEBnbWFpbC5jb20iLCJpYXQiOjE3MzE2NTAxMDksImV4cCI6MTczOTQyNjEwOX0.8krrYm5SnZJo7DzAtDgGI_Wp742OyeaTtBI00qFAhAk

@productId = coffee_f306c828-0674-4367-8d1d-26cd34896fb2


### add a product to favorites

# @name addFav
POST {{root}}/coffee_f306c828-0674-4367-8d1d-26cd34896fb2





### remove a product from favorites

# @name rmFav
DELETE {{root}}/{{productId}}





### get all favorites of mine

# @name favorites
GET {{root}}




### get if a product is fav of mine

# @name isFav
GET {{root}}/{{productId}}


