@linkbase = {{baseUrl}}/link
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzM2ZTIzYzljMWU5NjdmOWNlMGI5ODMiLCJlbWFpbCI6ImZhcmhhZEBnbWFpbC5jb20iLCJpYXQiOjE3NDYyNTcwNzksImV4cCI6MTc1NDAzMzA3OX0.QCJJeeQkNGWh-v5B8KjXciqSt5RK8CKHbnqUrsqjPnc


### create 

# @name create
POST {{linkbase}}
Content-Type: application/json
Authorization: {{authToken}}

{
    "products": [
        "tea_2021429e-cc49-4633-b143-f1f3458b0a2b",
        "tea_c2160ce2-1a7b-480d-abd2-dc1da245209f"
    ],
    "field": "weight"
}

### get

# @name get
GET {{linkbase}}/machine_f5ad986f-6cdf-4d62-8411-e37c69ba5363



### delete

# @name delete
DELETE {{linkbase}}/679bce858e6c10e22de43b03