@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjViMDQ3OTE4OGY0NjhjOTRmY2JkYmMiLCJlbWFpbCI6ImZhcmhhZC5zemRAZ21haWwuY29tIiwiaWF0IjoxNzMxNTkxNzkxLCJleHAiOjE3MzkzNjc3OTF9.1GWo8uv81Wh80mQ3R_TKDGWuqXvx5tHcS5ODHeBD2BU

@root = {{baseUrl}}/orders

@productA = coffee_85b5ee47-a732-4d19-aed8-ec93eb80a108
@productB = accessory_7e6d3080-1f15-4fff-ac12-6a95c8d1f8dd

### create a new order
@deliveryAddress = 67388a335a6eddd19fa90f4f

# @name order
POST {{root}}
Content-Type: application/json
Authorization: {{authToken}}

{
    "language": "en",
    "order": {
        "customer": {
            "name": "Farhad Seyfulla",
            "phone": "+994557367001"
        },
        "deliveryMethod": "delivery",
        "deliveryAddress": "{{deliveryAddress}}",
        "deliveryHour": "15:00", 
        "deliveryDate": "2024-12-03",
        "paymentMethod": "card",
        "items": [
            {
                "product": "{{productA}}",
                "quantity": 1
            },
            {
                "product": "{{productB}}",
                "quantity": 2
            }
        ]
    }
}






### create a new delivery order

# @name order
POST {{root}}
Content-Type: application/json
Authorization: {{authToken}}

{
    "language": "en",
    "order": {
        "customer": {
            "name": "Farhad Seyfulla",
            "phone": "+994557367001"
        },
        "deliveryMethod": "pickup",
        "paymentMethod": "cash",
        
        "items": [
            {
                "product": "{{productB}}",
                "quantity": 2
            }
        ]
    }
}





### my orders

# @name orders
GET {{root}}
Content-Type: application/json
Authorization: {{authToken}}





### find order by id

# @name byId
GET {{root}}/{{orders.response.body.data.orders[0]._id}}
Content-Type: application/json
Authorization: {{authToken}}
