@root = {{baseUrl}}/products
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjViMDQ3OTE4OGY0NjhjOTRmY2JkYmMiLCJlbWFpbCI6ImZhcmhhZC5zemRAZ21haWwuY29tIiwiaWF0IjoxNzMxNDg4ODAzLCJleHAiOjE3MzkyNjQ4MDN9.G3RGtq85pCTTWiXP3v8x-FC7w85HfmVE1PV9BsfLahU


// NOTICE: valid product types: Coffee, Accessory, Machine

### find products (default product type - ptp is set to Coffee)
# @name products
GET {{root}}?ptp=Coffee&lt=15



### find accessories
GET {{root}}?ptp=Accessory



### find machines
GET {{root}}?ptp=Machine




### Find ceffees limit 5
GET {{root}}?lt=15&pg=1&ptp=Coffee
Authorization: {{authToken}}




### update a product

@productId = coffee_34713695-619c-4062-8db1-05c4f30a642d

# @name update
PATCH {{baseUrl}}/products/{{productId}}
Content-Type: application/json
Authorization: {{authToken}}

{
    "product": {
        "attributes": [
        {
          "name": {
            "az": "Qovurma dərəcəsi",
            "en": "Roasting level",
            "ru": "Степень обжарки"
          },
          "value": {
            "az": "Orta",
            "en": "Mid",
            "ru": "Средняя"
          }
        },
        {
          "name": {
            "az": "Qovurma dərəcəsi",
            "en": "Roasting level",
            "ru": "Степень обжарки"
          },
          "value": {
            "az": "Orta",
            "en": "Mid",
            "ru": "Средняя"
          }
        }
      ]
    }
}




### delete product

@productId = coffee_34713695-619c-4062-8db1-05c4f30a642d
# @name delete
DELETE {{baseUrl}}/products/{{productId}}
Authorization: {{authToken}}




### rate product

@productId = coffee_34713695-619c-4062-8db1-05c4f30a642d

# @name rate
POST {{root}}/{{productId}}/rate 
Content-Type: application/json
Authorization: {{authToken}}

{
    "rating": 5
}








### order by price asc

GET {{root}}?ptp=Coffee&price=asc&lt=15


### order by price desc

GET {{root}}?ptp=Coffee&price=desc&lt=15


### find products order by rating asc

GET {{root}}?ptp=Coffee&rating=asc

### find products order by rating desc

GET {{root}}?ptp=Coffee&rating=desc


### by single processing methods

GET {{root}}?ptp=Coffee&processingMethod=Yuyulmuş&processingMethodLang=az


### by multiple processing methods

GET {{root}}?ptp=Coffee&processingMethod=washed,natural


### by single country

GET {{root}}?ptp=Coffee&country=Columbia


### by multiple country

GET {{root}}?ptp=Coffee&country=Colombia,Kenya


### order by Q-Grader asc

GET {{root}}?ptp=Coffee&qGrader=asc

### order by Q-Grader desc

GET {{root}}?ptp=Coffee&qGrader=desc


### by acidity levels

GET {{root}}?ptp=Coffee&acidity=low,medium


### by viscocity levels

GET {{root}}?ptp=Coffee&viscocity=low,medium

### by coffee types
GET {{root}}?ptp=Coffee&coffeeType=bright filter


### bright espresso
GET {{root}}?ptp=Coffee&coffeeType=bright espresso


### get processing methods
GET {{root}}/processing-methods
